#!/bin/bash

echo "Enter the first number:"
read num1

echo "Enter the second number:"
read num2

echo "Before swapping: First number is $num1 and second number is $num2"

# Swapping the numbers
temp=$num1
num1=$num2
num2=$temp

echo "After swapping: First number is $num1 and second number is $num2"
